
export const songs = [
  {
    id: '1',
    artists: 'Jessica Gonzalez', // Tên ca sĩ
    duration: 24, // thời gian tính theo giây
    image: require('../../../img/Audio Listing - Search Results/Image 84.png'), // Đường dẫn ảnh
    link: require('../../../songs/20th Century Fox hand fart intro_Audio_128k.m4a'), // Đường dẫn file nhạc
    name: '20th Century', // Tên bài hát
    size: 4.2, // Dung lượng file nhạc
    views: '1.2M views', // Số lượt xem
  },
  {
    id: '2',
    artists: 'Anthony Taylor',
    duration: 234,
    image: require('../../../img/Audio Listing - Search Results/Image 86.png'),
    link: require('../../../songs/Counting Stars_Audio_128k.m4a'),
    name: 'Shape of You',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '3',
    artists: 'Brian Bailey',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Blinding Lights',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '4',
    artists: 'Diana Cooper',
    duration: 129,
    image: require('../../../img/Audio Listing - Search Results/Image 88.png'),
    link: require('../../../songs/Jacques Offenbach _ Can Can Cover _Handfarts__Audio_128k.m4a'),
    name: 'Dance Monkey',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '5',
    artists: 'Diane Scott',
    duration: 276,
    image: require('../../../img/Audio Listing - Search Results/Image 89.png'),
    link: require('../../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
    name: 'Don\'t Start Now',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '6',
    artists: 'Dorothy Williams',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Someone You Loved',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '7',
    artists: 'Eugene Ramirez',
    duration: 276,
    image: require('../../../img/Audio Listing - Search Results/Image 89.png'),
    link: require('../../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '8',
    artists: 'Eugene Ramirez',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '9',
    artists: 'Eugene Ramirez',
    duration: 276,
    image: require('../../../img/Audio Listing - Search Results/Image 89.png'),
    link: require('../../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '10',
    artists: 'Eugene Ramirez',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '11',
    artists: 'Eugene Ramirez',
    duration: 276,
    image: require('../../../img/Audio Listing - Search Results/Image 89.png'),
    link: require('../../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '12',
    artists: 'Eugene Ramirez',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '13',
    artists: 'Eugene Ramirez',
    duration: 276,
    image: require('../../../img/Audio Listing - Search Results/Image 89.png'),
    link: require('../../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '14',
    artists: 'Eugene Ramirez',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '15',
    artists: 'Eugene Ramirez',
    duration: 276,
    image: require('../../../img/Audio Listing - Search Results/Image 89.png'),
    link: require('../../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
  {
    id: '16',
    artists: 'Eugene Ramirez',
    duration: 199,
    image: require('../../../img/Audio Listing - Search Results/Image 87.png'),
    link: require('../../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
    name: 'Memories',
    size: 4.2,
    views: '1.2M views',
  },
];


export default songs;