const songs = [
    {
      id: '1',
      title: 'Flower',
      artist: 'Jessica Gonzalez',
      duration: '0:24',
      file: require('../../songs/20th Century Fox hand fart intro_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 87.png'),
      views: "2M1",
    },
    {
      id: '2',
      title: 'Shape of You',
      artist: 'Anthony Taylor',
      duration: '3:54',
      file: require('../../songs/Counting Stars_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 84.png'),
      views: "2M1",
    },
    {
      id: '3',
      title: 'Blinding Lights',
      artist: 'Brian Bailey',
      duration: '3:19',
      file: require('../../songs/Gesaffelstein & The Weeknd _ Lost in the Fire _Official Video__Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 84.png'),
      views: "2M1",

    },
    {
      id: '4',
      title: 'Dance Monkey',
      artist: 'Diana Cooper',
      duration: '2:09',
      file: require('../../songs/Jacques Offenbach _ Can Can Cover _Handfarts__Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 88.png'),
      views: "2M1",

    },
    {
      id: '5',
      title: 'Don\'t Start Now',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",

    },
    {
      id: '6',
      title: 'Perfect',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
    {
      id: '7',
      title: 'Havana',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
    {
      id: '8',
      title: 'Senorita',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
    {
      id: '9',
      title: 'Bad Guy',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
    {
      id: '10',
      title: 'Old Town Road',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
    {
      id: '11',
      title: 'Someone You Loved',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
    {
      id: '12',
      title: 'Sicko Mode',
      artist: 'Diane Scott',
      duration: '4:36',
      file: require('../../songs/SƠN TÙNG M_TP _ CHÚNG TA CỦA TƯƠNG LAI _ OFFICIAL MUSIC VIDEO_Audio_128k.m4a'),
      image: require('../../img/Audio Listing - Search Results/Image 86.png'),
      views: "2M1",
    },
  ];
  
  export default songs;